# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OwnLocal Demos
email: jorge@ownlocal.com
description: > # this means to ignore newlines until "baseurl:"
  A place to showcase our wonderful products.
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
theme: minima

collections:
  products:
  prototypes:
  languages:
    output: true
    
locales:

  # ENGLISH
  en:
    directory_home: Directory Home
    businesses: Businesses
    ads: Ads
    categories: Categories
    back_to: Back to
    admin_login: Admin Login
    add_business: Add Business
    directory: Directory
    search_for_businesses: Search for businesses
    home: Home
    terms_of_service: Terms
    privacy_policy: Privacy
    go_to_top: Go To Top
    powered_by: Powered by
    footer_text: <span>– helping local media with innovative <a href="http://ownlocal.com/platform" target="_blank">print to web</a> and directory software</span>
    call: Call
    directions: Directions
    website: Website
    share: Share
    directions_tooltip: Get directions to this<br>location on Google Maps.
    website_tooltip: Open website<br>in new tab.
    email: Email
    print_ads: Print Ads
    valid: Valid
    homepage:
      hero_text: Find the <strong>best places</strong> <span>in
      suggested_searches: Restaurants,Beauty salons,General contractors,Legal services
      explore: Explore
      food: Food
      shopping: Shopping
      utilities: Utilities
      lawn: Lawn
      auto: Auto
      medical: Medical
      clothing: Clothing
      nightlife: Nightlife
      real_estate: Real Estate
      more: More
    business:
      share_tooltip: Share this business<br>on social media.
      share_this_business_on: Share this business on
      about: About
      business_hours: Business Hours
      monday: Monday
      tuesday: Tuesday
      wednesday: Wednesday
      thursday: Thursday
      friday: Friday
      saturday: Saturday
      sunday: Sunday
      testimonials: Testimonials
      video: Video
      helpful_links: Helpful Links
      follow_us: Follow Us
      coupon: Coupon
      question_or_comment: "Question or Comment?"
      name: Name
      message: Message
      submit: Submit
      photos: Photos
    ad:
      date: Date
      active_ad: Active Ad
      full_profile: Full Profile
      download: Download
      share_this_ad_on: Share this ad on
      text: Text

  # ESPAÑOL
  es:
    directory_home: Portada de directorio
    businesses: Negocios
    ads: Anuncios
    categories: Categorías
    back_to: Regresar a
    admin_login: Entrar como administrador
    add_business: Agregar negocio
    directory: Directorio
    search_for_businesses: Search for businesses
    home: Portada
    terms_of_service: Términos
    privacy_policy: Privacidad
    go_to_top: Regresar arriba
    powered_by: Un producto de
    footer_text: <span>– ayudando a los medios de comunicación locales con <a href="http://ownlocal.com/platform" target="_blank">software de publicidad</a></span>
    call: Llamar
    directions: Direcciones
    website: Sitio web
    share: Compartir
    directions_tooltip: Direcciones en Google Maps.
    website_tooltip: Abrir sitio web<br>en una pestaña nueva.
    email: Correo electrónico
    print_ads: Anuncios impresos
    valid: Vigente
    homepage:
      hero_text: Encuentre <strong>lo mejor</strong> <span> en
      suggested_searches: Restaurantes,Salones de belleza,Contratistas,Servicios legales
      explore: Explorar
      food: Comida
      shopping: Compras
      utilities: Utilidades
      lawn: Jardín
      auto: Auto
      medical: Salud
      clothing: Ropa
      nightlife: Bares
      real_estate: Inmuebles
      more: Más
    business:
      share_tooltip: Comparta este negocio<br>en las redes sociales.
      share_this_business_on: Comparta este negocio en
      about: Información
      business_hours: Horario de operación
      monday: Lunes
      tuesday: Martes
      wednesday: Miércoles
      thursday: Jueves
      friday: Viernes
      saturday: Sábado
      sunday: Domingo
      testimonials: Testimonios
      video: Video
      helpful_links: Ligas útiles
      follow_us: Síganos en Facebook
      coupon: Cupón
      question_or_comment: "Contáctenos"
      name: Nombre
      message: Mensaje
      submit: Enviar
      photos: Fotos
    ad:
      date: Fecha
      active_ad: Anuncio vigente
      full_profile: Perfil completo
      download: Descargar
      share_this_ad_on: Comparta este anuncio en
      text: Texto

    
countries:

  # UNITED STATES
  us:
    publisher_name: Baltimore Sun
    publisher_folder_name: baltimoresun
    publisher_url: baltimoresun.com
    publisher_city: Baltimore
    publisher_state: MD
    publisher_lat: 39.285168
    publisher_lon: -76.617256
    publisher_zoom: 17
    business_name: "Clyde's"
    business_address_one: 10221 Wincopin Circle
    business_address_two: Columbia, MD 21044
    business_city: Columbia
    business_state: MD
    business_lat: 39.215334
    business_lon: -76.856056
    # business_zoom: 12
    business_zip: 21044
    business_phone: (410) 730-2829
    business_phone_stripped: +14107302829
    business_website: clydes.com/columbia
    business_category: Restaurants
    business_subcategory: American Food
    business_description: "<p>Whether you live in or are visiting Washington, DC, Virginia or Maryland, Clyde's Restaurants are where you'll find a home away from home. Clyde's is a family of restaurants born from a sincere belief that great dining begins with fresh ingredients, friendly people and an unforgettable atmosphere.</p><p>We were one of the first in Washington to feature locally-raised and sustainable foods. In addition to our local and farm-grown produce, our legendary burgers are made using hormone-free, farm-raised beef sourced in the area and our chicken is antibiotic-free and hormone-free. Visit us and taste to believe.</p>"
    business_monday_hours: 11:00 AM - 2:00 AM
    business_tuesday_hours: 11:00 AM - 2:00 AM
    business_wednesday_hours: 11:00 AM - 2:00 AM
    business_thursday_hours: 11:00 AM - 2:00 AM
    business_friday_hours: 11:00 AM - 2:00 AM
    business_saturday_hours: 10:00 AM - 2:00 AM
    business_sunday_hours: 10:00 AM - 2:00 AM
    business_testimonial_one_text: "Been coming to this location for years.  A great spot to come before a Merriweather concert.  There's a great selection of draft beer and the menu has something for everyone."
    business_testimonial_one_name: Daniel (9/10/16)
    business_testimonial_two_text: "Great classy atmosphere, loved the Salmon burger, and once you're done enjoying your food, you've got the lakefront right next door to enjoy!"
    business_testimonial_two_name: Hugh (8/14/16)
    business_youtube_id: r5FdXKs8ats
    # business_sidengo_url: sidengo.com/mightyfineburgers  
    business_helpful_link_one_text: Restaurants in Columbia MD
    business_helpful_link_one_url: clydes.com/columbia#About
    business_helpful_link_two_text: American Food in Columbia MD
    business_helpful_link_two_url: clydes.com/columbia#Menus
    business_helpful_link_three_text: Bar and Grill Restaurants in Columbia MD
    business_helpful_link_three_url: clydes.com/columbia#Events
    business_facebook_username: ClydesRestaurant
    business_coupon_title: September Lobster Special
    business_coupon_description: "Whole Main Lobster: $16.95"
    business_coupon_expiration: "Valid until 9/30/16"
    business_ad_date_one: "Sep-12-16"
    business_ad_date_two: "Sep-08-16"
    business_ad_date_three: "Sep-05-16"
    business_ad_date_four: "Sep-02-16"
    business_ad_date_five: "Sep-01-16"
    business_ad_date_six: "Aug-30-16"
    ad_date: "September 12, 2016"
    expires_on_text: "Expires on<br>October 12, 2016 (30 days)"
    ad_text: "JUST THE SIGHT OF THEM MAKES BUTTER MELT. WHOLE MAINE LOBSTER $16.95 SEPTEMBER WHILE SUPPLIES LAST. MONTHLY Clyde's SPECIALS www.clydes.com CHEVY CHASE • COLUMBIA • GALLERY PLACE • GEORGETOWN • MARK CENTER RESTON • TOWER OAKS LODGE • TYSONS CORNER • WILLOW CREEK FARM"
  
  # MEXICO
  mx:
    publisher_name: El Norte
    publisher_folder_name: elnorte
    publisher_url: elnorte.com
    publisher_city: Monterrey
    publisher_state: NL
    publisher_lat: 25.6718502
    publisher_lon: -100.3054479
    publisher_zoom: 18
    business_name: La Nacional
    business_address_one: Ave. San Jerónimo 1106, Colonia Miravalle
    business_address_two: Monterrey, NL 64634
    business_city: Monterrey
    business_state: NL
    business_lat: 25.674095
    business_lon: -100.366193
    business_zoom: 15
    business_zip: 64634
    business_phone: +52 (81) 8347 9205
    business_phone_stripped: +528183479205
    business_website: lanacional.net
    business_category: Restaurantes
    business_subcategory: Comida Mexicana
    business_description: "<p>La Nacional nace en el 2003 con la firme intención de rescatar las tradiciones de la gastronomía local y las recetas de los pueblos de México, es una oportunidad para deleitar a nuestros comensales con lo que siempre se ha comido en éste hermoso país.</p><p>Dentro del Concepto de Cantina Mexicana hemos procurado dar todas las opciones de bebidas, es por eso que vendemos todos los productos de Grupo Modelo y Cervecería Cuauhtémoc Moctezuma.</p>"
    business_monday_hours: 12:30 PM - 1:00 AM
    business_tuesday_hours: 12:30 PM - 1:00 AM
    business_wednesday_hours: 12:30 PM - 1:00 AM
    business_thursday_hours: 12:30 PM - 1:00 AM
    business_friday_hours: 12:30 PM - 2:00 AM
    business_saturday_hours: 12:30 PM - 2:00 AM
    business_sunday_hours: 12:30 PM - 12:00 AM
    business_testimonial_one_text: "Anoche fuimos a cenar y desde que entramos fue excelente el trato, nuestro mecero nos hiso varias observaciones que sin duda ayudaron a que nuestra elección fuera la mejor. El rib eye, el chicharron... los jarritos todo delicioso, sin duda debemos volver por mas."
    business_testimonial_one_name: Fernando (30/08/16)
    business_testimonial_two_text: "El mejor lugar para comer carnes en Monterrey les súper recomiendo la alcachofa los frijoles el chicharrón bueno todo, los postres son riquísimos recomiendo mucho el de nuez. Vale la pena lo que se paga."
    business_testimonial_two_name: Daniela (10/08/16)
    business_youtube_id: 20DeJr6U6aI
    business_sidengo_url: sidengo.com/lanacional  
    business_helpful_link_one_text: Restaurantes en Monterrey NL
    business_helpful_link_one_url: lanacional.net/mobile/index2.php?tipo=0
    business_helpful_link_two_text: Cantinas en Monterrey NL
    business_helpful_link_two_url: lanacional.net/mobile/concepto.php
    business_helpful_link_three_text: Bares en Monterrey NL
    business_helpful_link_three_url: lanacional.net/mobile/elmenu.php
    business_facebook_username: lanacionalmx
    business_coupon_title: ¡2x1 en cervezas nacionales!
    business_coupon_description: "De lunes a jueves antes de las 5pm."
    business_coupon_expiration: "Válido hasta el 30/09/16"
    business_ad_date_one: "31/08/16"
    business_ad_date_two: "26/08/16"
    business_ad_date_three: "23/08/16"
    business_ad_date_four: "18/08/16"
    business_ad_date_five: "15/08/16"
    business_ad_date_six: "09/08/16"
    ad_date: "31 de agosto, 2016"
    expires_on_text: "Este anuncio está vigente <br>hasta el 30 de septiembre, 2016."
    ad_text: "Barbacoa de arrachera – Ave. San Jerónimo 1106 Colonia Miravalle. Reserva +52 (81) 8347 9205 @lanacionalmx"
    
  # EL SALVADOR
  sv:
    publisher_name: El Diario de Hoy
    publisher_folder_name: elsavador
    publisher_url: elsalvador.com
    publisher_city: San Salvador
    publisher_state: SV
    publisher_lat: 13.6985651
    publisher_lon: -89.2131213
    publisher_zoom: 11
    business_name: La Nacional
    business_address_one: Ave. San Jerónimo 1106, Colonia Miravalle
    business_address_two: Monterrey, NL 64634
    business_city: Monterrey
    business_state: NL
    business_lat: 25.674095
    business_lon: -100.366193
    business_zoom: 15
    business_zip: 64634
    business_phone: +52 (81) 8347 9205
    business_phone_stripped: +528183479205
    business_website: lanacional.net
    business_category: Restaurantes
    business_subcategory: Comida Mexicana
    business_description: "<p>La Nacional nace en el 2003 con la firme intención de rescatar las tradiciones de la gastronomía local y las recetas de los pueblos de México, es una oportunidad para deleitar a nuestros comensales con lo que siempre se ha comido en éste hermoso país.</p><p>Dentro del Concepto de Cantina Mexicana hemos procurado dar todas las opciones de bebidas, es por eso que vendemos todos los productos de Grupo Modelo y Cervecería Cuauhtémoc Moctezuma.</p>"
    business_monday_hours: 12:30 PM - 1:00 AM
    business_tuesday_hours: 12:30 PM - 1:00 AM
    business_wednesday_hours: 12:30 PM - 1:00 AM
    business_thursday_hours: 12:30 PM - 1:00 AM
    business_friday_hours: 12:30 PM - 2:00 AM
    business_saturday_hours: 12:30 PM - 2:00 AM
    business_sunday_hours: 12:30 PM - 12:00 AM
    business_testimonial_one_text: "Anoche fuimos a cenar y desde que entramos fue excelente el trato, nuestro mecero nos hiso varias observaciones que sin duda ayudaron a que nuestra elección fuera la mejor. El rib eye, el chicharron... los jarritos todo delicioso, sin duda debemos volver por mas."
    business_testimonial_one_name: Fernando (30/08/16)
    business_testimonial_two_text: "El mejor lugar para comer carnes en Monterrey les súper recomiendo la alcachofa los frijoles el chicharrón bueno todo, los postres son riquísimos recomiendo mucho el de nuez. Vale la pena lo que se paga."
    business_testimonial_two_name: Daniela (10/08/16)
    business_youtube_id: 20DeJr6U6aI
    business_sidengo_url: sidengo.com/lanacional  
    business_helpful_link_one_text: Restaurantes en Monterrey NL
    business_helpful_link_one_url: lanacional.net/mobile/index2.php?tipo=0
    business_helpful_link_two_text: Cantinas en Monterrey NL
    business_helpful_link_two_url: lanacional.net/mobile/concepto.php
    business_helpful_link_three_text: Bares en Monterrey NL
    business_helpful_link_three_url: lanacional.net/mobile/elmenu.php
    business_facebook_username: lanacionalmx
    business_coupon_title: ¡2x1 en cervezas nacionales!
    business_coupon_description: "De lunes a jueves antes de las 5pm."
    business_coupon_expiration: "Válido hasta el 30/09/16"
    business_ad_date_one: "31/08/16"
    business_ad_date_two: "26/08/16"
    business_ad_date_three: "23/08/16"
    business_ad_date_four: "18/08/16"
    business_ad_date_five: "15/08/16"
    business_ad_date_six: "09/08/16"
    ad_date: "31 de agosto, 2016"
    expires_on_text: "Este anuncio está vigente <br>hasta el 30 de septiembre, 2016."
    ad_text: "Barbacoa de arrachera – Ave. San Jerónimo 1106 Colonia Miravalle. Reserva +52 (81) 8347 9205 @lanacionalmx"