# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OwnLocal Demos
email: jorge@ownlocal.com
description: > # this means to ignore newlines until "baseurl:"
  A place to showcase our wonderful products.
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
theme: minima

collections:
  products:
  prototypes:
  languages:
    output: true
    
locales:
  en:
    directory_home: Directory Home
    businesses: Businesses
    ads: Ads
    categories: Categories
    back_to: Back to
    admin_login: Admin Login
    add_business: Add Business
    directory: Directory
    search_for_businesses: Search for businesses
    home: Home
    terms_of_service: Terms of Service
    privacy_policy: Privacy Policy
    go_to_top: Go To Top
    powered_by: Powered by
    footer_text: <span>– helping local media with innovative <a href="http://ownlocal.com/platform" target="_blank">print to web</a> and directory software</span>
    call: Call
    directions: Directions
    website: Website
    share: Share
    directions_tooltip: Get directions to this<br>location on Google Maps.
    website_tooltip: Open website<br>in new tab.
    email: Email
    print_ads: Print Ads
    valid: Valid
    homepage:
      hero_text: Find the <strong>best places</strong> <span>in
      suggested_searches: Restaurants,Beauty salons,General contractors,Legal services
      explore: Explore
      food: Food
      shopping: Shopping
      utilities: Utilities
      lawn: Lawn
      auto: Auto
      medical: Medical
      clothing: Clothing
      nightlife: Nightlife
      real_estate: Real Estate
      more: More
    business:
      share_tooltip: Share this business<br>on social media.
      share_this_business_on: Share this business on
      about: About
      business_hours: Business Hours
      monday: Monday
      tuesday: Tuesday
      wednesday: Wednesday
      thursday: Thursday
      friday: Friday
      saturday: Saturday
      sunday: Sunday
      testimonials: Testimonials
      video: Video
      helpful_links: Helpful Links
      follow_us: Follow Us
      coupon: Coupon
      question_or_comment: "Question or Comment?"
      name: Name
      message: Message
      submit: Submit
      photos: Photos
    ad:
      date: Date
      active_ad: Active Ad
      full_profile: Full Profile
      download: Download
      share_this_ad_on: Share this ad on
      text: Text
    
countries:
  us:
    publisher_name: Baltimore Sun
    publisher_folder_name: baltimoresun
    publisher_url: baltimoresun.com
    publisher_logo: /images/publishers/statesman/logo.png
    publisher_city: Baltimore
    publisher_state: MD
    publisher_lat: 39.285168
    publisher_lon: -76.617256
    publisher_zoom: 17
    business_name: "Clyde's"
    business_address_one: 10221 Wincopin Circle
    business_address_two: Columbia, MD 21044
    business_city: Columbia
    business_state: MD
    business_lat: 39.215334
    business_lon: -76.856056
    business_zip: 21044
    business_phone: (410) 730-2829
    business_phone_stripped: +14107302829
    business_website: clydes.com/columbia
    business_category: Restaurants
    business_subcategory: American Food
    business_description: "<p>Whether you live in or are visiting Washington, DC, Virginia or Maryland, Clyde's Restaurants are where you'll find a home away from home. Clyde's is a family of restaurants born from a sincere belief that great dining begins with fresh ingredients, friendly people and an unforgettable atmosphere.</p><p>We were one of the first in Washington to feature locally-raised and sustainable foods. In addition to our local and farm-grown produce, our legendary burgers are made using hormone-free, farm-raised beef sourced in the area and our chicken is antibiotic-free and hormone-free. Visit us and taste to believe.</p>"
    business_monday_hours: 11:00 AM - 2:00 AM
    business_tuesday_hours: 11:00 AM - 2:00 AM
    business_wednesday_hours: 11:00 AM - 2:00 AM
    business_thursday_hours: 11:00 AM - 2:00 AM
    business_friday_hours: 11:00 AM - 2:00 AM
    business_saturday_hours: 10:00 AM - 2:00 AM
    business_sunday_hours: 10:00 AM - 2:00 AM
    business_testimonial_one_text: "Been coming to this location for years.  A great spot to come before a Merriweather concert.  There's a great selection of draft beer and the menu has something for everyone."
    business_testimonial_one_name: Daniel (9/10/16)
    business_testimonial_two_text: "Great classy atmosphere, loved the Salmon burger, and once you're done enjoying your food, you've got the lakefront right next door to enjoy!"
    business_testimonial_two_name: Hugh (8/14/16)
    business_youtube_id: r5FdXKs8ats
    # business_sidengo_url: sidengo.com/mightyfineburgers  
    business_helpful_link_one_text: Restaurants in Columbia MD
    business_helpful_link_one_url: clydes.com/columbia#About
    business_helpful_link_two_text: American Food in Columbia MD
    business_helpful_link_two_url: clydes.com/columbia#Menus
    business_helpful_link_three_text: Bar and Grill Restaurants in Columbia MD
    business_helpful_link_three_url: clydes.com/columbia#Events
    business_facebook_username: ClydesRestaurant
    business_coupon_title: September Lobster Special
    business_coupon_description: "Whole Main Lobster: $16.95"
    business_coupon_expiration: "Valid until 9/30/16"
    business_ad_date_one: "Sep-12-16"
    business_ad_date_two: "Sep-08-16"
    business_ad_date_three: "Sep-05-16"
    business_ad_date_four: "Sep-02-16"
    business_ad_date_five: "Sep-01-16"
    business_ad_date_six: "Aug-30-16"
    ad_date: "September 12, 2016"
    expires_on_text: "Expires on<br>October 12, 2016 (30 days)"
    ad_text: "JUST THE SIGHT OF THEM MAKES BUTTER MELT. WHOLE MAINE LOBSTER $16.95 SEPTEMBER WHILE SUPPLIES LAST. MONTHLY Clyde's SPECIALS www.clydes.com CHEVY CHASE • COLUMBIA • GALLERY PLACE • GEORGETOWN • MARK CENTER RESTON • TOWER OAKS LODGE • TYSONS CORNER • WILLOW CREEK FARM"