# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OwnLocal Demos
email: jorge@ownlocal.com
description: > # this means to ignore newlines until "baseurl:"
  A place to showcase our wonderful products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: ownlocal
github_username:  gonzalezmedina

# Build settings
markdown: kramdown
theme: minima

collections:
  products:
  prototypes:
  languages:
    output: true
    
locales:
  en:
    directory_home: Directory Home
    businesses: Businesses
    ads: Ads
    categories: Categories
    back_to: Back to
    admin_login: Admin Login
    add_business: Add Business
    directory: Directory
    search_for_businesses: Search for businesses
    home: Home
    terms_of_service: Terms of Service
    privacy_policy: Privacy Policy
    go_to_top: Go To Top
    powered_by: Powered by
    footer_text: <span>– helping local media with innovative <a href="http://ownlocal.com/platform" target="_blank">print to web</a> and directory software</span>
    call: Call
    homepage:
      hero_text: Find the <strong>best places</strong> <span>in
      suggested_searches: Restaurants,Beauty salons,General contractors,Legal services
      explore: Explore
      food: Food
      shopping: Shopping
      utilities: Utilities
      lawn: Lawn
      auto: Auto
      medical: Medical
      clothing: Clothing
      nightlife: Nightlife
      real_estate: Real Estate
      more: More
    business:
    ad:
    
countries:
  us:
    publisher_name: Austin American Statesman
    publisher_url: statesman.com
    publisher_logo: /images/publishers/statesman/logo.png
    publisher_city: Austin
    publisher_state: TX
    publisher_lat: 30.263556
    publisher_lon: -97.744316
    publisher_zoom: 16
    business_name: Toy Joy
    business_address_one: 403 W 2nd St
    business_address_two: Austin, TX 78701
    business_city: Austin
    business_state: TX
    business_lat: 0
    business_lon: 0
    business_zip: 78701
    business_phone: (512) 320-0090
    business_website: toyjoy.com
    business_category: Shopping
    business_subcategory: Game & Toy Stores
    business_description: <p>An Austin original, Toy Joy has been keeping Austin fun since 1987. Know for it's floor to ceiling (including the ceiling!) eclectic collection of the fun, collectible, nostalgic and "a little bit weird" toys and gifts, Toy Joy has been serving locals and worldwide visitors for over 28 years. We have gifts and toys for "kids" of all ages and in all price ranges. While we are a less than typical children's retailer you can find gifts here from newborns to the adult young-at-heart.</p>